# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d21e773fd351bd5b479b12f3a0a2810a"
application_url = "https://rowflow.unbundl.com"
embedded = true
name = "RowFlow"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://rowflow.unbundl.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
